### ISSUE TITLE
Awesome work! When the training code will be released?

### ISSUE THREAD

**Issue by manyuan97** [Picsart-AI-Research/StreamingT2V#13]

**Comment by oldnaari** [comment]
Thank you for your interest in this project, and apologies for the delayed response.

At this time, we do not plan to release the training code in the near future due to its complexity and our current limited resources. However, we may reconsider this in the future when our capacity allows.

If you remain interested or have any other questions, feel free to reach out, and we’ll be happy to assist. I am closing this issue for now, but any additional questions regarding the training can be discussed in a separate issue.
